/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-02-15 17:18:02 UTC)
 * on 2017-03-16 at 07:10:15 UTC 
 * Modify at your own risk.
 */

package com.mycompany.services.tweetentityendpoint;

/**
 * Service definition for Tweetentityendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link TweetentityendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Tweetentityendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.21.0 of the tweetentityendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://whosaidthatontwitter.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "tweetentityendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Tweetentityendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Tweetentityendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getTweetEntity".
   *
   * This request holds the parameters needed by the tweetentityendpoint server.  After setting any
   * optional parameters, call the {@link GetTweetEntity#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetTweetEntity getTweetEntity(java.lang.Long id) throws java.io.IOException {
    GetTweetEntity result = new GetTweetEntity(id);
    initialize(result);
    return result;
  }

  public class GetTweetEntity extends TweetentityendpointRequest<com.mycompany.services.tweetentityendpoint.model.TweetEntity> {

    private static final String REST_PATH = "tweetentity/{id}";

    /**
     * Create a request for the method "getTweetEntity".
     *
     * This request holds the parameters needed by the the tweetentityendpoint server.  After setting
     * any optional parameters, call the {@link GetTweetEntity#execute()} method to invoke the remote
     * operation. <p> {@link GetTweetEntity#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetTweetEntity(java.lang.Long id) {
      super(Tweetentityendpoint.this, "GET", REST_PATH, null, com.mycompany.services.tweetentityendpoint.model.TweetEntity.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetTweetEntity setAlt(java.lang.String alt) {
      return (GetTweetEntity) super.setAlt(alt);
    }

    @Override
    public GetTweetEntity setFields(java.lang.String fields) {
      return (GetTweetEntity) super.setFields(fields);
    }

    @Override
    public GetTweetEntity setKey(java.lang.String key) {
      return (GetTweetEntity) super.setKey(key);
    }

    @Override
    public GetTweetEntity setOauthToken(java.lang.String oauthToken) {
      return (GetTweetEntity) super.setOauthToken(oauthToken);
    }

    @Override
    public GetTweetEntity setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetTweetEntity) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetTweetEntity setQuotaUser(java.lang.String quotaUser) {
      return (GetTweetEntity) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetTweetEntity setUserIp(java.lang.String userIp) {
      return (GetTweetEntity) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetTweetEntity setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetTweetEntity set(String parameterName, Object value) {
      return (GetTweetEntity) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertTweetEntity".
   *
   * This request holds the parameters needed by the tweetentityendpoint server.  After setting any
   * optional parameters, call the {@link InsertTweetEntity#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.mycompany.services.tweetentityendpoint.model.TweetEntity}
   * @return the request
   */
  public InsertTweetEntity insertTweetEntity(com.mycompany.services.tweetentityendpoint.model.TweetEntity content) throws java.io.IOException {
    InsertTweetEntity result = new InsertTweetEntity(content);
    initialize(result);
    return result;
  }

  public class InsertTweetEntity extends TweetentityendpointRequest<com.mycompany.services.tweetentityendpoint.model.TweetEntity> {

    private static final String REST_PATH = "tweetentity";

    /**
     * Create a request for the method "insertTweetEntity".
     *
     * This request holds the parameters needed by the the tweetentityendpoint server.  After setting
     * any optional parameters, call the {@link InsertTweetEntity#execute()} method to invoke the
     * remote operation. <p> {@link InsertTweetEntity#initialize(com.google.api.client.googleapis.serv
     * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.mycompany.services.tweetentityendpoint.model.TweetEntity}
     * @since 1.13
     */
    protected InsertTweetEntity(com.mycompany.services.tweetentityendpoint.model.TweetEntity content) {
      super(Tweetentityendpoint.this, "POST", REST_PATH, content, com.mycompany.services.tweetentityendpoint.model.TweetEntity.class);
    }

    @Override
    public InsertTweetEntity setAlt(java.lang.String alt) {
      return (InsertTweetEntity) super.setAlt(alt);
    }

    @Override
    public InsertTweetEntity setFields(java.lang.String fields) {
      return (InsertTweetEntity) super.setFields(fields);
    }

    @Override
    public InsertTweetEntity setKey(java.lang.String key) {
      return (InsertTweetEntity) super.setKey(key);
    }

    @Override
    public InsertTweetEntity setOauthToken(java.lang.String oauthToken) {
      return (InsertTweetEntity) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertTweetEntity setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertTweetEntity) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertTweetEntity setQuotaUser(java.lang.String quotaUser) {
      return (InsertTweetEntity) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertTweetEntity setUserIp(java.lang.String userIp) {
      return (InsertTweetEntity) super.setUserIp(userIp);
    }

    @Override
    public InsertTweetEntity set(String parameterName, Object value) {
      return (InsertTweetEntity) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listTweetEntity".
   *
   * This request holds the parameters needed by the tweetentityendpoint server.  After setting any
   * optional parameters, call the {@link ListTweetEntity#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListTweetEntity listTweetEntity() throws java.io.IOException {
    ListTweetEntity result = new ListTweetEntity();
    initialize(result);
    return result;
  }

  public class ListTweetEntity extends TweetentityendpointRequest<com.mycompany.services.tweetentityendpoint.model.CollectionResponseTweetEntity> {

    private static final String REST_PATH = "tweetentity";

    /**
     * Create a request for the method "listTweetEntity".
     *
     * This request holds the parameters needed by the the tweetentityendpoint server.  After setting
     * any optional parameters, call the {@link ListTweetEntity#execute()} method to invoke the remote
     * operation. <p> {@link ListTweetEntity#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListTweetEntity() {
      super(Tweetentityendpoint.this, "GET", REST_PATH, null, com.mycompany.services.tweetentityendpoint.model.CollectionResponseTweetEntity.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListTweetEntity setAlt(java.lang.String alt) {
      return (ListTweetEntity) super.setAlt(alt);
    }

    @Override
    public ListTweetEntity setFields(java.lang.String fields) {
      return (ListTweetEntity) super.setFields(fields);
    }

    @Override
    public ListTweetEntity setKey(java.lang.String key) {
      return (ListTweetEntity) super.setKey(key);
    }

    @Override
    public ListTweetEntity setOauthToken(java.lang.String oauthToken) {
      return (ListTweetEntity) super.setOauthToken(oauthToken);
    }

    @Override
    public ListTweetEntity setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListTweetEntity) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListTweetEntity setQuotaUser(java.lang.String quotaUser) {
      return (ListTweetEntity) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListTweetEntity setUserIp(java.lang.String userIp) {
      return (ListTweetEntity) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListTweetEntity setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListTweetEntity setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListTweetEntity set(String parameterName, Object value) {
      return (ListTweetEntity) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeTweetEntity".
   *
   * This request holds the parameters needed by the tweetentityendpoint server.  After setting any
   * optional parameters, call the {@link RemoveTweetEntity#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveTweetEntity removeTweetEntity(java.lang.Long id) throws java.io.IOException {
    RemoveTweetEntity result = new RemoveTweetEntity(id);
    initialize(result);
    return result;
  }

  public class RemoveTweetEntity extends TweetentityendpointRequest<Void> {

    private static final String REST_PATH = "tweetentity/{id}";

    /**
     * Create a request for the method "removeTweetEntity".
     *
     * This request holds the parameters needed by the the tweetentityendpoint server.  After setting
     * any optional parameters, call the {@link RemoveTweetEntity#execute()} method to invoke the
     * remote operation. <p> {@link RemoveTweetEntity#initialize(com.google.api.client.googleapis.serv
     * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveTweetEntity(java.lang.Long id) {
      super(Tweetentityendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveTweetEntity setAlt(java.lang.String alt) {
      return (RemoveTweetEntity) super.setAlt(alt);
    }

    @Override
    public RemoveTweetEntity setFields(java.lang.String fields) {
      return (RemoveTweetEntity) super.setFields(fields);
    }

    @Override
    public RemoveTweetEntity setKey(java.lang.String key) {
      return (RemoveTweetEntity) super.setKey(key);
    }

    @Override
    public RemoveTweetEntity setOauthToken(java.lang.String oauthToken) {
      return (RemoveTweetEntity) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveTweetEntity setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveTweetEntity) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveTweetEntity setQuotaUser(java.lang.String quotaUser) {
      return (RemoveTweetEntity) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveTweetEntity setUserIp(java.lang.String userIp) {
      return (RemoveTweetEntity) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveTweetEntity setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveTweetEntity set(String parameterName, Object value) {
      return (RemoveTweetEntity) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateTweetEntity".
   *
   * This request holds the parameters needed by the tweetentityendpoint server.  After setting any
   * optional parameters, call the {@link UpdateTweetEntity#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.mycompany.services.tweetentityendpoint.model.TweetEntity}
   * @return the request
   */
  public UpdateTweetEntity updateTweetEntity(com.mycompany.services.tweetentityendpoint.model.TweetEntity content) throws java.io.IOException {
    UpdateTweetEntity result = new UpdateTweetEntity(content);
    initialize(result);
    return result;
  }

  public class UpdateTweetEntity extends TweetentityendpointRequest<com.mycompany.services.tweetentityendpoint.model.TweetEntity> {

    private static final String REST_PATH = "tweetentity";

    /**
     * Create a request for the method "updateTweetEntity".
     *
     * This request holds the parameters needed by the the tweetentityendpoint server.  After setting
     * any optional parameters, call the {@link UpdateTweetEntity#execute()} method to invoke the
     * remote operation. <p> {@link UpdateTweetEntity#initialize(com.google.api.client.googleapis.serv
     * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.mycompany.services.tweetentityendpoint.model.TweetEntity}
     * @since 1.13
     */
    protected UpdateTweetEntity(com.mycompany.services.tweetentityendpoint.model.TweetEntity content) {
      super(Tweetentityendpoint.this, "PUT", REST_PATH, content, com.mycompany.services.tweetentityendpoint.model.TweetEntity.class);
    }

    @Override
    public UpdateTweetEntity setAlt(java.lang.String alt) {
      return (UpdateTweetEntity) super.setAlt(alt);
    }

    @Override
    public UpdateTweetEntity setFields(java.lang.String fields) {
      return (UpdateTweetEntity) super.setFields(fields);
    }

    @Override
    public UpdateTweetEntity setKey(java.lang.String key) {
      return (UpdateTweetEntity) super.setKey(key);
    }

    @Override
    public UpdateTweetEntity setOauthToken(java.lang.String oauthToken) {
      return (UpdateTweetEntity) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateTweetEntity setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateTweetEntity) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateTweetEntity setQuotaUser(java.lang.String quotaUser) {
      return (UpdateTweetEntity) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateTweetEntity setUserIp(java.lang.String userIp) {
      return (UpdateTweetEntity) super.setUserIp(userIp);
    }

    @Override
    public UpdateTweetEntity set(String parameterName, Object value) {
      return (UpdateTweetEntity) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Tweetentityendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Tweetentityendpoint}. */
    @Override
    public Tweetentityendpoint build() {
      return new Tweetentityendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link TweetentityendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setTweetentityendpointRequestInitializer(
        TweetentityendpointRequestInitializer tweetentityendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(tweetentityendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
